version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    branches:
     only:
       - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c6:1b:99:34:0b:14:3a:5d:80:1c:ce:ab:fd:43:99:c4"
      - checkout
          name: Install
          command: yarn install
      - run: 
          name: Build
          command: yarn build